# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - app-service-02

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        working-directory: ./application
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Create deployment package
        run: |
          mkdir deployment
          cp application/dist/* deployment/ -r
          cp application/node_modules deployment/ -r
          cp application/package.json deployment/
          cp application/package-lock.json deployment/
          cd deployment
          zip -r release.zip .
          mv release.zip ../

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_68F5B1674F2E43BC93465FEDB92A8AF4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_005EF4AA23BB4FE8996FA3240D02B818 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4CF303CD6B474FB5A44D8843E6BAC8D0 }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'app-service-02'
          slot-name: 'Production'
          package: .
          
